# Generated by Django 6.0.5 on 2026-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='applied_offer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
